import { Router } from "express";
import { publicController } from "../controllers/publicController";
import { asyncHandler } from "../lib/asyncHandler";
import { requireAuth } from "../middleware/auth";
import { validate } from "../middleware/validate";
import { slugParamSchema } from "../validators/common";
import { accountRouter } from "./accountRoutes";
import { activityRouter } from "./activityRoutes";
import { appointmentRouter } from "./appointmentRoutes";
import { authRouter } from "./authRoutes";
import { calendarRouter } from "./calendarRoutes";
import { clientRouter } from "./clientRoutes";
import { communicationsRouter } from "./communicationsRoutes";
import { dashboardRouter } from "./dashboardRoutes";
import { healthRouter } from "./healthRoutes";
import { internalRouter } from "./internalRoutes";
import { offDayRouter } from "./offDayRoutes";
import { paymentMethodsRouter } from "./paymentMethodsRoutes";
import { photoRouter } from "./photoRoutes";
import { profileRouter } from "./profileRoutes";
import { publicRouter } from "./publicRoutes";
import { rebookNudgeRouter } from "./rebookNudgeRoutes";
import { reminderRouter } from "./reminderRoutes";
import { serviceRouter } from "./serviceRoutes";
import { settingsRouter } from "./settingsRoutes";
import { thankYouEmailRouter } from "./thankYouEmailRoutes";
import { waitlistRouter } from "./waitlistRoutes";

export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.get("/book/:slug", validate({ params: slugParamSchema }), asyncHandler(publicController.redirectToBookingPage));
apiRouter.use("/api/public", publicRouter);
apiRouter.use("/api/communications", communicationsRouter);
apiRouter.use("/internal", internalRouter);
apiRouter.use("/me", requireAuth);
apiRouter.use("/api", requireAuth);

apiRouter.use(authRouter);
apiRouter.use("/api/account", accountRouter);
apiRouter.use("/api/activity", activityRouter);
apiRouter.use("/api/clients", clientRouter);
apiRouter.use("/api/appointments", appointmentRouter);
apiRouter.use("/api/calendar", calendarRouter);
apiRouter.use("/api/photos", photoRouter);
apiRouter.use("/api/reminders", reminderRouter);
apiRouter.use("/api/dashboard", dashboardRouter);
apiRouter.use("/api/off-days", offDayRouter);
apiRouter.use("/api/payment-methods", paymentMethodsRouter);
apiRouter.use("/api/profile", profileRouter);
apiRouter.use("/api/rebook-nudges", rebookNudgeRouter);
apiRouter.use("/api/services", serviceRouter);
apiRouter.use("/api/settings", settingsRouter);
apiRouter.use("/api/thank-you-emails", thankYouEmailRouter);
apiRouter.use("/api/waitlist", waitlistRouter);
