import { randomUUID } from "crypto";
import { ApiError } from "../lib/errors";
import { supabaseAdmin } from "../lib/supabase";

export const PAYMENT_METHOD_QRS_BUCKET = "payment-method-qrs";
export const PAYMENT_METHOD_QR_ALLOWED_CONTENT_TYPES = ["image/png", "image/jpeg", "image/webp"] as const;
export const PAYMENT_METHOD_QR_MAX_BYTES = 5 * 1024 * 1024;
export const PAYMENT_METHOD_QR_UPLOAD_EXPIRES_IN_SECONDS = 2 * 60 * 60;
export const PAYMENT_METHOD_QR_SIGNED_READ_EXPIRES_IN_SECONDS = 5 * 60;

type PaymentMethodQrContentType = (typeof PAYMENT_METHOD_QR_ALLOWED_CONTENT_TYPES)[number];

const EXTENSIONS_BY_CONTENT_TYPE: Record<PaymentMethodQrContentType, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp"
};
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const QR_PATH_PATTERN = new RegExp(
  `^(${UUID_PATTERN.source.slice(1, -1)})/(${UUID_PATTERN.source.slice(1, -1)})\\.(png|jpg|webp)$`,
  "i"
);

type StorageErrorShape = {
  message?: string;
  statusCode?: string | number;
  error?: string;
};

const STORAGE_DELETE_BATCH_SIZE = 100;

const isMissingObjectError = (error: StorageErrorShape | null): boolean => {
  const statusCode = typeof error?.statusCode === "number" ? String(error.statusCode) : error?.statusCode;
  return statusCode === "404" || /not found/i.test(error?.message ?? "");
};

const toStorageApiErrorDetails = (error: StorageErrorShape | null) =>
  error
    ? {
        message: error.message,
        statusCode: error.statusCode,
        error: error.error
      }
    : undefined;

const getExtensionForContentType = (contentType: string): string => {
  if (!PAYMENT_METHOD_QR_ALLOWED_CONTENT_TYPES.includes(contentType as PaymentMethodQrContentType)) {
    throw new ApiError(400, "Unsupported payment shortcut QR content type");
  }

  return EXTENSIONS_BY_CONTENT_TYPE[contentType as PaymentMethodQrContentType];
};

export const paymentMethodQrStorageService = {
  bucket: PAYMENT_METHOD_QRS_BUCKET,

  generateStoragePath(userId: string, contentType: string): string {
    const extension = getExtensionForContentType(contentType);
    return `${userId}/${randomUUID()}.${extension}`;
  },

  assertQrPathMatches(userId: string, storagePath: string | null | undefined): void {
    if (!storagePath) {
      return;
    }

    const match = storagePath.match(QR_PATH_PATTERN);
    if (!match || match[1].toLowerCase() !== userId.toLowerCase()) {
      throw new ApiError(400, "Payment shortcut QR path must be generated by this account");
    }
  },

  async createSignedReadUrl(
    storagePath: string,
    expiresInSeconds = PAYMENT_METHOD_QR_SIGNED_READ_EXPIRES_IN_SECONDS
  ): Promise<string> {
    const { data, error } = await supabaseAdmin
      .storage
      .from(PAYMENT_METHOD_QRS_BUCKET)
      .createSignedUrl(storagePath, expiresInSeconds);

    if (error) {
      throw new ApiError(500, "Unable to create payment shortcut QR read URL", toStorageApiErrorDetails(error));
    }

    return data.signedUrl;
  },

  async createUploadIntent(userId: string, payload: {
    content_type: string;
    size_bytes: number;
  }): Promise<{
    upload_url: string;
    storage_path: string;
    expires_in: number;
  }> {
    if (payload.size_bytes > PAYMENT_METHOD_QR_MAX_BYTES) {
      throw new ApiError(400, "Payment shortcut QR image exceeds maximum size");
    }

    const storagePath = this.generateStoragePath(userId, payload.content_type);
    const { data, error } = await supabaseAdmin
      .storage
      .from(PAYMENT_METHOD_QRS_BUCKET)
      .createSignedUploadUrl(storagePath);

    if (error) {
      throw new ApiError(500, "Unable to create payment shortcut QR upload URL", toStorageApiErrorDetails(error));
    }

    return {
      upload_url: data.signedUrl,
      storage_path: storagePath,
      expires_in: PAYMENT_METHOD_QR_UPLOAD_EXPIRES_IN_SECONDS
    };
  },

  async deleteUserPrefix(userId: string): Promise<{ deletedPaths: string[]; failedPaths: string[] }> {
    const prefix = userId;
    const paths: string[] = [];
    let offset = 0;

    for (;;) {
      const { data, error } = await supabaseAdmin.storage.from(PAYMENT_METHOD_QRS_BUCKET).list(prefix, {
        limit: STORAGE_DELETE_BATCH_SIZE,
        offset,
        sortBy: { column: "name", order: "asc" }
      });
      if (error) throw new ApiError(500, "Unable to list payment shortcut QR objects", toStorageApiErrorDetails(error));
      const objects = data ?? [];
      if (objects.length === 0) break;
      for (const object of objects) {
        const record = object as unknown as Record<string, unknown>;
        if (record.id !== null && record.id !== undefined && record.metadata) {
          paths.push(`${prefix}/${String(record.name ?? "")}`);
        }
      }
      if (objects.length < STORAGE_DELETE_BATCH_SIZE) break;
      offset += objects.length;
    }

    const deletedPaths: string[] = [];
    const failedPaths: string[] = [];
    for (let index = 0; index < paths.length; index += STORAGE_DELETE_BATCH_SIZE) {
      const batch = paths.slice(index, index + STORAGE_DELETE_BATCH_SIZE);
      const { error } = await supabaseAdmin.storage.from(PAYMENT_METHOD_QRS_BUCKET).remove(batch);
      if (error && !isMissingObjectError(error)) {
        failedPaths.push(...batch);
      } else {
        deletedPaths.push(...batch);
      }
    }

    return { deletedPaths, failedPaths };
  }
};
